export const data = [
  {
    category: 'food',
    comments: 'Comentário',
    date: '2021-07-01',
    id: '1',
    name: 'Almoço',
    paymentMethod: 'ticket',
    price: 25,
  },
  {
    category: 'transport',
    comments: 'Comentário',
    date: '2021-07-01',
    id: '2',
    installments: 12,
    name: 'Uber',
    paymentMethod: 'credit',
    price: 25,
  },
  {
    category: 'health',
    comments: 'Comentário',
    date: '2021-07-01',
    id: '3',
    installments: 1,
    name: 'Plano de saúde',
    paymentMethod: 'credit',
    price: 25,
  },
  {
    category: 'entertainment',
    comments: 'Comentário',
    date: '2021-07-01',
    id: '4',
    installments: 1,
    name: 'Netflix',
    paymentMethod: 'credit',
    price: 25,
  },
  {
    category: 'education',
    comments: 'Comentário',
    date: '2021-07-01',
    id: '5',
    name: 'Curso de inglês',
    paymentMethod: 'pix',
    price: 25,
  },
  {
    category: 'other',
    comments: 'asdsdasdasdasddddddddddddddddd adsdddddddddd',
    date: '2021-07-01',
    id: '6',
    name: 'Outro',
    paymentMethod: 'debit',
    price: 25,
  },
]
